### PR TITLE
Purescript 0.13

### PR DESCRIPTION
**Pull request by jvliwanag**
Upgrade to purescript 0.13
Upgrade of aws-sdk and other js and purescript deps

Had to remove support for `apiVersions` since this was causing failing tests. I'll update aws options to union record types in a future pull req building on this.

### CODE REVIEW

**Comment by plippe** [comment]
You are a GOD

**Comment by jvliwanag** [comment]
Finally got it to build 😄 Looking to use a record/union based API on a diff pull request so that the projects in the `gen` project can have a simpler api.

**Comment by plippe** [comment]
This looks great, thanks for being awesome

I have two small change requests: 
- Would you mind adding `apiVersions` to the `Missing service options` in the readme ?
- Would you mind bumping the [version](https://github.com/purescript-aws-sdk/purescript-aws-request/blob/master/Makefile#L4) ?

**Comment by jvliwanag** [comment]
I still have a branch I'm working on over [here](https://github.com/jvliwanag/purescript-aws-request/tree/record-based-options) which restores the apiVersions among others, but also changes the api's quite a bit. I'm continuing to update that branch as I work on a viable update for the `gen` project. Perhaps once that pull req lands, we can then bump the version? Or if you prefer we do that now, that would be alright as well.

**Comment by plippe** [comment]
I think you are in full control.
You just tell me when you want to merge, and I will click the button.

**Comment by jvliwanag** [comment]
Suggesting we merge this first just to get the purescript 0.13 out of the way. Will follow up sometime next week on another pull req with the rest.

**Comment by plippe** [comment]
Thanks for the help

**Pull request merged**
